spring:
  application:
    name: analytics-890-service
  datasource:
    url: jdbc:postgresql://localhost:3306/analytics-890_db
    username: appadmin
    password: Secure@321
  server:
    port: 8890
