spring:
  application:
    name: analytics-593-service
  datasource:
    url: jdbc:postgresql://localhost:3306/analytics-593_db
    username: appadmin
    password: Secure@321
  server:
    port: 8593
