spring:
  application:
    name: analytics-886-service
  datasource:
    url: jdbc:postgresql://localhost:3306/analytics-886_db
    username: webadmin
    password: Secure@321
  server:
    port: 8886
