spring:
  application:
    name: analytics-155-service
  datasource:
    url: jdbc:postgresql://localhost:3306/analytics-155_db
    username: appadmin
    password: Secure@321
  server:
    port: 8155
