spring:
  application:
    name: analytics-614-service
  datasource:
    url: jdbc:postgresql://localhost:3306/analytics-614_db
    username: appadmin
    password: Secure@321
  server:
    port: 8614
