spring:
  application:
    name: analytics-289-service
  datasource:
    url: jdbc:postgresql://localhost:3306/analytics-289_db
    username: appadmin
    password: Secure@321
  server:
    port: 8289
