spring:
  application:
    name: analytics-420-service
  datasource:
    url: jdbc:postgresql://localhost:3306/analytics-420_db
    username: webadmin
    password: Secure@321
  server:
    port: 8420
