spring:
  application:
    name: analytics-637-service
  datasource:
    url: jdbc:postgresql://localhost:3306/analytics-637_db
    username: webadmin
    password: Secure@321
  server:
    port: 8637
