spring:
  application:
    name: analytics-207-service
  datasource:
    url: jdbc:postgresql://localhost:3306/analytics-207_db
    username: webadmin
    password: Secure@321
  server:
    port: 8207
