spring:
  application:
    name: analytics-355-service
  datasource:
    url: jdbc:postgresql://localhost:3306/analytics-355_db
    username: webadmin
    password: Secure@321
  server:
    port: 8355
