spring:
  application:
    name: analytics-122-service
  datasource:
    url: jdbc:postgresql://localhost:3306/analytics-122_db
    username: appadmin
    password: Secure@321
  server:
    port: 8122
