spring:
  application:
    name: analytics-765-service
  datasource:
    url: jdbc:postgresql://localhost:3306/analytics-765_db
    username: appadmin
    password: Secure@321
  server:
    port: 8765
