spring:
  application:
    name: analytics-873-service
  datasource:
    url: jdbc:postgresql://localhost:3306/analytics-873_db
    username: webadmin
    password: Secure@321
  server:
    port: 8873
