spring:
  application:
    name: analytics-437-service
  datasource:
    url: jdbc:postgresql://localhost:3306/analytics-437_db
    username: appadmin
    password: Secure@321
  server:
    port: 8437
