spring:
  application:
    name: analytics-531-service
  datasource:
    url: jdbc:postgresql://localhost:3306/analytics-531_db
    username: appadmin
    password: Secure@321
  server:
    port: 8531
