spring:
  application:
    name: analytics-328-service
  datasource:
    url: jdbc:postgresql://localhost:3306/analytics-328_db
    username: webadmin
    password: Secure@321
  server:
    port: 8328
