spring:
  application:
    name: analytics-141-service
  datasource:
    url: jdbc:postgresql://localhost:3306/analytics-141_db
    username: appadmin
    password: Secure@321
  server:
    port: 8141
