spring:
  application:
    name: analytics-462-service
  datasource:
    url: jdbc:postgresql://localhost:3306/analytics-462_db
    username: appadmin
    password: Secure@321
  server:
    port: 8462
