spring:
  application:
    name: analytics-476-service
  datasource:
    url: jdbc:postgresql://localhost:3306/analytics-476_db
    username: webadmin
    password: Secure@321
  server:
    port: 8476
