spring:
  application:
    name: analytics-907-service
  datasource:
    url: jdbc:postgresql://localhost:3306/analytics-907_db
    username: webadmin
    password: Secure@321
  server:
    port: 8907
