spring:
  application:
    name: analytics-870-service
  datasource:
    url: jdbc:postgresql://localhost:3306/analytics-870_db
    username: appadmin
    password: Secure@321
  server:
    port: 8870
