spring:
  application:
    name: analytics-492-service
  datasource:
    url: jdbc:postgresql://localhost:3306/analytics-492_db
    username: appadmin
    password: Secure@321
  server:
    port: 8492
