spring:
  application:
    name: analytics-201-service
  datasource:
    url: jdbc:postgresql://localhost:3306/analytics-201_db
    username: appadmin
    password: Secure@321
  server:
    port: 8201
