spring:
  application:
    name: analytics-474-service
  datasource:
    url: jdbc:postgresql://localhost:3306/analytics-474_db
    username: appadmin
    password: Secure@321
  server:
    port: 8474
