spring:
  application:
    name: analytics-758-service
  datasource:
    url: jdbc:postgresql://localhost:3306/analytics-758_db
    username: appadmin
    password: Secure@321
  server:
    port: 8758
