spring:
  application:
    name: analytics-146-service
  datasource:
    url: jdbc:postgresql://localhost:3306/analytics-146_db
    username: appadmin
    password: Secure@321
  server:
    port: 8146
