spring:
  application:
    name: analytics-498-service
  datasource:
    url: jdbc:postgresql://localhost:3306/analytics-498_db
    username: appadmin
    password: Secure@321
  server:
    port: 8498
