spring:
  application:
    name: analytics-549-service
  datasource:
    url: jdbc:postgresql://localhost:3306/analytics-549_db
    username: webadmin
    password: Secure@321
  server:
    port: 8549
