spring:
  application:
    name: analytics-270-service
  datasource:
    url: jdbc:postgresql://localhost:3306/analytics-270_db
    username: appadmin
    password: Secure@321
  server:
    port: 8270
