spring:
  application:
    name: analytics-535-service
  datasource:
    url: jdbc:postgresql://localhost:3306/analytics-535_db
    username: webadmin
    password: Secure@321
  server:
    port: 8535
