spring:
  application:
    name: analytics-494-service
  datasource:
    url: jdbc:postgresql://localhost:3306/analytics-494_db
    username: appadmin
    password: Secure@321
  server:
    port: 8494
