spring:
  application:
    name: analytics-308-service
  datasource:
    url: jdbc:postgresql://localhost:3306/analytics-308_db
    username: appadmin
    password: Secure@321
  server:
    port: 8308
