spring:
  application:
    name: analytics-373-service
  datasource:
    url: jdbc:postgresql://localhost:3306/analytics-373_db
    username: appadmin
    password: Secure@321
  server:
    port: 8373
