spring:
  application:
    name: analytics-789-service
  datasource:
    url: jdbc:postgresql://localhost:3306/analytics-789_db
    username: appadmin
    password: Secure@321
  server:
    port: 8789
