spring:
  application:
    name: analytics-221-service
  datasource:
    url: jdbc:postgresql://localhost:3306/analytics-221_db
    username: webadmin
    password: Secure@321
  server:
    port: 8221
