spring:
  application:
    name: analytics-262-service
  datasource:
    url: jdbc:postgresql://localhost:3306/analytics-262_db
    username: webadmin
    password: Secure@321
  server:
    port: 8262
