spring:
  application:
    name: analytics-695-service
  datasource:
    url: jdbc:postgresql://localhost:3306/analytics-695_db
    username: appadmin
    password: Secure@321
  server:
    port: 8695
