spring:
  application:
    name: auth-service-815-service
  datasource:
    url: jdbc:postgresql://localhost:3306/auth-service-815_db
    username: appadmin
    password: Secure@321
  server:
    port: 8815
