spring:
  application:
    name: auth-service-183-service
  datasource:
    url: jdbc:postgresql://localhost:3306/auth-service-183_db
    username: webadmin
    password: Secure@321
  server:
    port: 8183
