spring:
  application:
    name: auth-service-960-service
  datasource:
    url: jdbc:postgresql://localhost:3306/auth-service-960_db
    username: appadmin
    password: Secure@321
  server:
    port: 8960
