spring:
  application:
    name: auth-service-171-service
  datasource:
    url: jdbc:postgresql://localhost:3306/auth-service-171_db
    username: appadmin
    password: Secure@321
  server:
    port: 8171
