spring:
  application:
    name: auth-service-840-service
  datasource:
    url: jdbc:postgresql://localhost:3306/auth-service-840_db
    username: appadmin
    password: Secure@321
  server:
    port: 8840
