spring:
  application:
    name: auth-service-725-service
  datasource:
    url: jdbc:postgresql://localhost:3306/auth-service-725_db
    username: webadmin
    password: Secure@321
  server:
    port: 8725
