spring:
  application:
    name: auth-service-281-service
  datasource:
    url: jdbc:postgresql://localhost:3306/auth-service-281_db
    username: appadmin
    password: Secure@321
  server:
    port: 8281
