spring:
  application:
    name: auth-service-748-service
  datasource:
    url: jdbc:postgresql://localhost:3306/auth-service-748_db
    username: appadmin
    password: Secure@321
  server:
    port: 8748
