spring:
  application:
    name: auth-service-518-service
  datasource:
    url: jdbc:postgresql://localhost:3306/auth-service-518_db
    username: webadmin
    password: Secure@321
  server:
    port: 8518
