spring:
  application:
    name: auth-service-574-service
  datasource:
    url: jdbc:postgresql://localhost:3306/auth-service-574_db
    username: webadmin
    password: Secure@321
  server:
    port: 8574
