spring:
  application:
    name: auth-service-787-service
  datasource:
    url: jdbc:postgresql://localhost:3306/auth-service-787_db
    username: appadmin
    password: Secure@321
  server:
    port: 8787
