spring:
  application:
    name: auth-service-416-service
  datasource:
    url: jdbc:postgresql://localhost:3306/auth-service-416_db
    username: appadmin
    password: Secure@321
  server:
    port: 8416
