spring:
  application:
    name: auth-service-69-service
  datasource:
    url: jdbc:postgresql://localhost:3306/auth-service-69_db
    username: webadmin
    password: Secure@321
  server:
    port: 8069
