spring:
  application:
    name: auth-service-792-service
  datasource:
    url: jdbc:postgresql://localhost:3306/auth-service-792_db
    username: webadmin
    password: Secure@321
  server:
    port: 8792
