spring:
  application:
    name: auth-service-360-service
  datasource:
    url: jdbc:postgresql://localhost:3306/auth-service-360_db
    username: webadmin
    password: Secure@321
  server:
    port: 8360
