spring:
  application:
    name: auth-service-384-service
  datasource:
    url: jdbc:postgresql://localhost:3306/auth-service-384_db
    username: appadmin
    password: Secure@321
  server:
    port: 8384
