spring:
  application:
    name: auth-service-762-service
  datasource:
    url: jdbc:postgresql://localhost:3306/auth-service-762_db
    username: webadmin
    password: Secure@321
  server:
    port: 8762
