spring:
  application:
    name: auth-service-339-service
  datasource:
    url: jdbc:postgresql://localhost:3306/auth-service-339_db
    username: appadmin
    password: Secure@321
  server:
    port: 8339
