spring:
  application:
    name: auth-service-841-service
  datasource:
    url: jdbc:postgresql://localhost:3306/auth-service-841_db
    username: appadmin
    password: Secure@321
  server:
    port: 8841
