spring:
  application:
    name: auth-service-449-service
  datasource:
    url: jdbc:postgresql://localhost:3306/auth-service-449_db
    username: webadmin
    password: Secure@321
  server:
    port: 8449
