spring:
  application:
    name: auth-service-807-service
  datasource:
    url: jdbc:postgresql://localhost:3306/auth-service-807_db
    username: appadmin
    password: Secure@321
  server:
    port: 8807
