spring:
  application:
    name: auth-service-331-service
  datasource:
    url: jdbc:postgresql://localhost:3306/auth-service-331_db
    username: appadmin
    password: Secure@321
  server:
    port: 8331
