spring:
  application:
    name: auth-service-501-service
  datasource:
    url: jdbc:postgresql://localhost:3306/auth-service-501_db
    username: webadmin
    password: Secure@321
  server:
    port: 8501
