spring:
  application:
    name: auth-service-585-service
  datasource:
    url: jdbc:postgresql://localhost:3306/auth-service-585_db
    username: appadmin
    password: Secure@321
  server:
    port: 8585
