spring:
  application:
    name: auth-service-237-service
  datasource:
    url: jdbc:postgresql://localhost:3306/auth-service-237_db
    username: appadmin
    password: Secure@321
  server:
    port: 8237
