spring:
  application:
    name: auth-service-892-service
  datasource:
    url: jdbc:postgresql://localhost:3306/auth-service-892_db
    username: appadmin
    password: Secure@321
  server:
    port: 8892
