spring:
  application:
    name: auth-service-616-service
  datasource:
    url: jdbc:postgresql://localhost:3306/auth-service-616_db
    username: appadmin
    password: Secure@321
  server:
    port: 8616
