spring:
  application:
    name: auth-service-764-service
  datasource:
    url: jdbc:postgresql://localhost:3306/auth-service-764_db
    username: appadmin
    password: Secure@321
  server:
    port: 8764
