spring:
  application:
    name: auth-service-310-service
  datasource:
    url: jdbc:postgresql://localhost:3306/auth-service-310_db
    username: webadmin
    password: Secure@321
  server:
    port: 8310
