spring:
  application:
    name: auth-service-116-service
  datasource:
    url: jdbc:postgresql://localhost:3306/auth-service-116_db
    username: webadmin
    password: Secure@321
  server:
    port: 8116
