spring:
  application:
    name: auth-service-575-service
  datasource:
    url: jdbc:postgresql://localhost:3306/auth-service-575_db
    username: webadmin
    password: Secure@321
  server:
    port: 8575
