spring:
  application:
    name: auth-service-467-service
  datasource:
    url: jdbc:postgresql://localhost:3306/auth-service-467_db
    username: appadmin
    password: Secure@321
  server:
    port: 8467
