spring:
  application:
    name: auth-service-440-service
  datasource:
    url: jdbc:postgresql://localhost:3306/auth-service-440_db
    username: webadmin
    password: Secure@321
  server:
    port: 8440
