spring:
  application:
    name: auth-service-612-service
  datasource:
    url: jdbc:postgresql://localhost:3306/auth-service-612_db
    username: webadmin
    password: Secure@321
  server:
    port: 8612
