spring:
  application:
    name: auth-service-372-service
  datasource:
    url: jdbc:postgresql://localhost:3306/auth-service-372_db
    username: appadmin
    password: Secure@321
  server:
    port: 8372
