spring:
  application:
    name: auth-service-888-service
  datasource:
    url: jdbc:postgresql://localhost:3306/auth-service-888_db
    username: webadmin
    password: Secure@321
  server:
    port: 8888
