spring:
  application:
    name: inventory-553-service
  datasource:
    url: jdbc:postgresql://localhost:3306/inventory-553_db
    username: webadmin
    password: Secure@321
  server:
    port: 8553
