spring:
  application:
    name: inventory-214-service
  datasource:
    url: jdbc:postgresql://localhost:3306/inventory-214_db
    username: webadmin
    password: Secure@321
  server:
    port: 8214
