spring:
  application:
    name: inventory-288-service
  datasource:
    url: jdbc:postgresql://localhost:3306/inventory-288_db
    username: webadmin
    password: Secure@321
  server:
    port: 8288
