spring:
  application:
    name: inventory-520-service
  datasource:
    url: jdbc:postgresql://localhost:3306/inventory-520_db
    username: appadmin
    password: Secure@321
  server:
    port: 8520
