spring:
  application:
    name: inventory-573-service
  datasource:
    url: jdbc:postgresql://localhost:3306/inventory-573_db
    username: webadmin
    password: Secure@321
  server:
    port: 8573
