spring:
  application:
    name: inventory-329-service
  datasource:
    url: jdbc:postgresql://localhost:3306/inventory-329_db
    username: webadmin
    password: Secure@321
  server:
    port: 8329
