spring:
  application:
    name: inventory-188-service
  datasource:
    url: jdbc:postgresql://localhost:3306/inventory-188_db
    username: webadmin
    password: Secure@321
  server:
    port: 8188
