spring:
  application:
    name: inventory-487-service
  datasource:
    url: jdbc:postgresql://localhost:3306/inventory-487_db
    username: webadmin
    password: Secure@321
  server:
    port: 8487
