spring:
  application:
    name: inventory-495-service
  datasource:
    url: jdbc:postgresql://localhost:3306/inventory-495_db
    username: appadmin
    password: Secure@321
  server:
    port: 8495
