spring:
  application:
    name: inventory-872-service
  datasource:
    url: jdbc:postgresql://localhost:3306/inventory-872_db
    username: webadmin
    password: Secure@321
  server:
    port: 8872
