spring:
  application:
    name: inventory-690-service
  datasource:
    url: jdbc:postgresql://localhost:3306/inventory-690_db
    username: appadmin
    password: Secure@321
  server:
    port: 8690
