spring:
  application:
    name: inventory-880-service
  datasource:
    url: jdbc:postgresql://localhost:3306/inventory-880_db
    username: appadmin
    password: Secure@321
  server:
    port: 8880
