spring:
  application:
    name: inventory-263-service
  datasource:
    url: jdbc:postgresql://localhost:3306/inventory-263_db
    username: webadmin
    password: Secure@321
  server:
    port: 8263
