spring:
  application:
    name: inventory-691-service
  datasource:
    url: jdbc:postgresql://localhost:3306/inventory-691_db
    username: appadmin
    password: Secure@321
  server:
    port: 8691
