spring:
  application:
    name: inventory-723-service
  datasource:
    url: jdbc:postgresql://localhost:3306/inventory-723_db
    username: webadmin
    password: Secure@321
  server:
    port: 8723
