spring:
  application:
    name: inventory-772-service
  datasource:
    url: jdbc:postgresql://localhost:3306/inventory-772_db
    username: webadmin
    password: Secure@321
  server:
    port: 8772
