spring:
  application:
    name: inventory-507-service
  datasource:
    url: jdbc:postgresql://localhost:3306/inventory-507_db
    username: webadmin
    password: Secure@321
  server:
    port: 8507
