spring:
  application:
    name: inventory-923-service
  datasource:
    url: jdbc:postgresql://localhost:3306/inventory-923_db
    username: appadmin
    password: Secure@321
  server:
    port: 8923
