spring:
  application:
    name: inventory-388-service
  datasource:
    url: jdbc:postgresql://localhost:3306/inventory-388_db
    username: appadmin
    password: Secure@321
  server:
    port: 8388
