spring:
  application:
    name: inventory-714-service
  datasource:
    url: jdbc:postgresql://localhost:3306/inventory-714_db
    username: webadmin
    password: Secure@321
  server:
    port: 8714
