spring:
  application:
    name: inventory-822-service
  datasource:
    url: jdbc:postgresql://localhost:3306/inventory-822_db
    username: webadmin
    password: Secure@321
  server:
    port: 8822
