spring:
  application:
    name: inventory-893-service
  datasource:
    url: jdbc:postgresql://localhost:3306/inventory-893_db
    username: appadmin
    password: Secure@321
  server:
    port: 8893
