spring:
  application:
    name: inventory-453-service
  datasource:
    url: jdbc:postgresql://localhost:3306/inventory-453_db
    username: webadmin
    password: Secure@321
  server:
    port: 8453
