spring:
  application:
    name: inventory-267-service
  datasource:
    url: jdbc:postgresql://localhost:3306/inventory-267_db
    username: webadmin
    password: Secure@321
  server:
    port: 8267
