spring:
  application:
    name: inventory-143-service
  datasource:
    url: jdbc:postgresql://localhost:3306/inventory-143_db
    username: webadmin
    password: Secure@321
  server:
    port: 8143
