spring:
  application:
    name: inventory-565-service
  datasource:
    url: jdbc:postgresql://localhost:3306/inventory-565_db
    username: appadmin
    password: Secure@321
  server:
    port: 8565
