spring:
  application:
    name: inventory-367-service
  datasource:
    url: jdbc:postgresql://localhost:3306/inventory-367_db
    username: webadmin
    password: Secure@321
  server:
    port: 8367
