spring:
  application:
    name: inventory-577-service
  datasource:
    url: jdbc:postgresql://localhost:3306/inventory-577_db
    username: webadmin
    password: Secure@321
  server:
    port: 8577
