spring:
  application:
    name: inventory-365-service
  datasource:
    url: jdbc:postgresql://localhost:3306/inventory-365_db
    username: appadmin
    password: Secure@321
  server:
    port: 8365
