spring:
  application:
    name: inventory-965-service
  datasource:
    url: jdbc:postgresql://localhost:3306/inventory-965_db
    username: appadmin
    password: Secure@321
  server:
    port: 8965
