spring:
  application:
    name: inventory-832-service
  datasource:
    url: jdbc:postgresql://localhost:3306/inventory-832_db
    username: webadmin
    password: Secure@321
  server:
    port: 8832
