spring:
  application:
    name: inventory-322-service
  datasource:
    url: jdbc:postgresql://localhost:3306/inventory-322_db
    username: webadmin
    password: Secure@321
  server:
    port: 8322
