spring:
  application:
    name: inventory-413-service
  datasource:
    url: jdbc:postgresql://localhost:3306/inventory-413_db
    username: webadmin
    password: Secure@321
  server:
    port: 8413
