spring:
  application:
    name: inventory-244-service
  datasource:
    url: jdbc:postgresql://localhost:3306/inventory-244_db
    username: webadmin
    password: Secure@321
  server:
    port: 8244
