spring:
  application:
    name: inventory-247-service
  datasource:
    url: jdbc:postgresql://localhost:3306/inventory-247_db
    username: webadmin
    password: Secure@321
  server:
    port: 8247
