spring:
  application:
    name: inventory-314-service
  datasource:
    url: jdbc:postgresql://localhost:3306/inventory-314_db
    username: appadmin
    password: Secure@321
  server:
    port: 8314
