spring:
  application:
    name: inventory-311-service
  datasource:
    url: jdbc:postgresql://localhost:3306/inventory-311_db
    username: webadmin
    password: Secure@321
  server:
    port: 8311
