spring:
  application:
    name: inventory-173-service
  datasource:
    url: jdbc:postgresql://localhost:3306/inventory-173_db
    username: appadmin
    password: Secure@321
  server:
    port: 8173
