spring:
  application:
    name: notification-995-service
  datasource:
    url: jdbc:postgresql://localhost:3306/notification-995_db
    username: appadmin
    password: Secure@321
  server:
    port: 8995
