spring:
  application:
    name: notification-225-service
  datasource:
    url: jdbc:postgresql://localhost:3306/notification-225_db
    username: appadmin
    password: Secure@321
  server:
    port: 8225
