spring:
  application:
    name: notification-430-service
  datasource:
    url: jdbc:postgresql://localhost:3306/notification-430_db
    username: appadmin
    password: Secure@321
  server:
    port: 8430
