spring:
  application:
    name: notification-737-service
  datasource:
    url: jdbc:postgresql://localhost:3306/notification-737_db
    username: appadmin
    password: Secure@321
  server:
    port: 8737
