spring:
  application:
    name: notification-228-service
  datasource:
    url: jdbc:postgresql://localhost:3306/notification-228_db
    username: appadmin
    password: Secure@321
  server:
    port: 8228
