spring:
  application:
    name: notification-485-service
  datasource:
    url: jdbc:postgresql://localhost:3306/notification-485_db
    username: webadmin
    password: Secure@321
  server:
    port: 8485
