spring:
  application:
    name: notification-961-service
  datasource:
    url: jdbc:postgresql://localhost:3306/notification-961_db
    username: appadmin
    password: Secure@321
  server:
    port: 8961
