spring:
  application:
    name: notification-669-service
  datasource:
    url: jdbc:postgresql://localhost:3306/notification-669_db
    username: appadmin
    password: Secure@321
  server:
    port: 8669
