spring:
  application:
    name: notification-894-service
  datasource:
    url: jdbc:postgresql://localhost:3306/notification-894_db
    username: webadmin
    password: Secure@321
  server:
    port: 8894
