spring:
  application:
    name: notification-368-service
  datasource:
    url: jdbc:postgresql://localhost:3306/notification-368_db
    username: appadmin
    password: Secure@321
  server:
    port: 8368
