spring:
  application:
    name: notification-371-service
  datasource:
    url: jdbc:postgresql://localhost:3306/notification-371_db
    username: appadmin
    password: Secure@321
  server:
    port: 8371
