spring:
  application:
    name: notification-236-service
  datasource:
    url: jdbc:postgresql://localhost:3306/notification-236_db
    username: appadmin
    password: Secure@321
  server:
    port: 8236
