spring:
  application:
    name: notification-486-service
  datasource:
    url: jdbc:postgresql://localhost:3306/notification-486_db
    username: webadmin
    password: Secure@321
  server:
    port: 8486
