spring:
  application:
    name: notification-338-service
  datasource:
    url: jdbc:postgresql://localhost:3306/notification-338_db
    username: webadmin
    password: Secure@321
  server:
    port: 8338
