spring:
  application:
    name: notification-378-service
  datasource:
    url: jdbc:postgresql://localhost:3306/notification-378_db
    username: appadmin
    password: Secure@321
  server:
    port: 8378
