spring:
  application:
    name: notification-107-service
  datasource:
    url: jdbc:postgresql://localhost:3306/notification-107_db
    username: appadmin
    password: Secure@321
  server:
    port: 8107
