spring:
  application:
    name: notification-393-service
  datasource:
    url: jdbc:postgresql://localhost:3306/notification-393_db
    username: webadmin
    password: Secure@321
  server:
    port: 8393
