spring:
  application:
    name: notification-838-service
  datasource:
    url: jdbc:postgresql://localhost:3306/notification-838_db
    username: webadmin
    password: Secure@321
  server:
    port: 8838
