spring:
  application:
    name: notification-285-service
  datasource:
    url: jdbc:postgresql://localhost:3306/notification-285_db
    username: webadmin
    password: Secure@321
  server:
    port: 8285
