spring:
  application:
    name: notification-998-service
  datasource:
    url: jdbc:postgresql://localhost:3306/notification-998_db
    username: appadmin
    password: Secure@321
  server:
    port: 8998
