spring:
  application:
    name: notification-220-service
  datasource:
    url: jdbc:postgresql://localhost:3306/notification-220_db
    username: appadmin
    password: Secure@321
  server:
    port: 8220
