spring:
  application:
    name: notification-65-service
  datasource:
    url: jdbc:postgresql://localhost:3306/notification-65_db
    username: webadmin
    password: Secure@321
  server:
    port: 8065
