spring:
  application:
    name: notification-296-service
  datasource:
    url: jdbc:postgresql://localhost:3306/notification-296_db
    username: webadmin
    password: Secure@321
  server:
    port: 8296
