spring:
  application:
    name: notification-650-service
  datasource:
    url: jdbc:postgresql://localhost:3306/notification-650_db
    username: appadmin
    password: Secure@321
  server:
    port: 8650
