spring:
  application:
    name: notification-634-service
  datasource:
    url: jdbc:postgresql://localhost:3306/notification-634_db
    username: appadmin
    password: Secure@321
  server:
    port: 8634
