spring:
  application:
    name: notification-176-service
  datasource:
    url: jdbc:postgresql://localhost:3306/notification-176_db
    username: webadmin
    password: Secure@321
  server:
    port: 8176
