spring:
  application:
    name: notification-702-service
  datasource:
    url: jdbc:postgresql://localhost:3306/notification-702_db
    username: webadmin
    password: Secure@321
  server:
    port: 8702
