spring:
  application:
    name: notification-110-service
  datasource:
    url: jdbc:postgresql://localhost:3306/notification-110_db
    username: appadmin
    password: Secure@321
  server:
    port: 8110
