spring:
  application:
    name: notification-293-service
  datasource:
    url: jdbc:postgresql://localhost:3306/notification-293_db
    username: webadmin
    password: Secure@321
  server:
    port: 8293
