spring:
  application:
    name: notification-636-service
  datasource:
    url: jdbc:postgresql://localhost:3306/notification-636_db
    username: appadmin
    password: Secure@321
  server:
    port: 8636
