spring:
  application:
    name: notification-660-service
  datasource:
    url: jdbc:postgresql://localhost:3306/notification-660_db
    username: appadmin
    password: Secure@321
  server:
    port: 8660
