spring:
  application:
    name: notification-412-service
  datasource:
    url: jdbc:postgresql://localhost:3306/notification-412_db
    username: appadmin
    password: Secure@321
  server:
    port: 8412
