spring:
  application:
    name: notification-216-service
  datasource:
    url: jdbc:postgresql://localhost:3306/notification-216_db
    username: webadmin
    password: Secure@321
  server:
    port: 8216
