spring:
  application:
    name: notification-532-service
  datasource:
    url: jdbc:postgresql://localhost:3306/notification-532_db
    username: webadmin
    password: Secure@321
  server:
    port: 8532
