spring:
  application:
    name: notification-971-service
  datasource:
    url: jdbc:postgresql://localhost:3306/notification-971_db
    username: webadmin
    password: Secure@321
  server:
    port: 8971
