spring:
  application:
    name: notification-608-service
  datasource:
    url: jdbc:postgresql://localhost:3306/notification-608_db
    username: appadmin
    password: Secure@321
  server:
    port: 8608
