spring:
  application:
    name: notification-406-service
  datasource:
    url: jdbc:postgresql://localhost:3306/notification-406_db
    username: appadmin
    password: Secure@321
  server:
    port: 8406
