spring:
  application:
    name: notification-798-service
  datasource:
    url: jdbc:postgresql://localhost:3306/notification-798_db
    username: webadmin
    password: Secure@321
  server:
    port: 8798
