spring:
  application:
    name: notification-175-service
  datasource:
    url: jdbc:postgresql://localhost:3306/notification-175_db
    username: appadmin
    password: Secure@321
  server:
    port: 8175
