spring:
  application:
    name: notification-217-service
  datasource:
    url: jdbc:postgresql://localhost:3306/notification-217_db
    username: webadmin
    password: Secure@321
  server:
    port: 8217
