spring:
  application:
    name: notification-432-service
  datasource:
    url: jdbc:postgresql://localhost:3306/notification-432_db
    username: appadmin
    password: Secure@321
  server:
    port: 8432
