spring:
  application:
    name: reporting-845-service
  datasource:
    url: jdbc:postgresql://localhost:3306/reporting-845_db
    username: webadmin
    password: Secure@321
  server:
    port: 8845
