spring:
  application:
    name: reporting-500-service
  datasource:
    url: jdbc:postgresql://localhost:3306/reporting-500_db
    username: appadmin
    password: Secure@321
  server:
    port: 8500
