spring:
  application:
    name: reporting-814-service
  datasource:
    url: jdbc:postgresql://localhost:3306/reporting-814_db
    username: webadmin
    password: Secure@321
  server:
    port: 8814
