spring:
  application:
    name: reporting-670-service
  datasource:
    url: jdbc:postgresql://localhost:3306/reporting-670_db
    username: appadmin
    password: Secure@321
  server:
    port: 8670
