spring:
  application:
    name: reporting-602-service
  datasource:
    url: jdbc:postgresql://localhost:3306/reporting-602_db
    username: appadmin
    password: Secure@321
  server:
    port: 8602
