spring:
  application:
    name: reporting-382-service
  datasource:
    url: jdbc:postgresql://localhost:3306/reporting-382_db
    username: webadmin
    password: Secure@321
  server:
    port: 8382
