spring:
  application:
    name: reporting-443-service
  datasource:
    url: jdbc:postgresql://localhost:3306/reporting-443_db
    username: webadmin
    password: Secure@321
  server:
    port: 8443
