spring:
  application:
    name: reporting-856-service
  datasource:
    url: jdbc:postgresql://localhost:3306/reporting-856_db
    username: appadmin
    password: Secure@321
  server:
    port: 8856
