spring:
  application:
    name: reporting-513-service
  datasource:
    url: jdbc:postgresql://localhost:3306/reporting-513_db
    username: webadmin
    password: Secure@321
  server:
    port: 8513
