spring:
  application:
    name: reporting-312-service
  datasource:
    url: jdbc:postgresql://localhost:3306/reporting-312_db
    username: webadmin
    password: Secure@321
  server:
    port: 8312
