spring:
  application:
    name: reporting-342-service
  datasource:
    url: jdbc:postgresql://localhost:3306/reporting-342_db
    username: webadmin
    password: Secure@321
  server:
    port: 8342
