spring:
  application:
    name: reporting-239-service
  datasource:
    url: jdbc:postgresql://localhost:3306/reporting-239_db
    username: appadmin
    password: Secure@321
  server:
    port: 8239
