spring:
  application:
    name: reporting-545-service
  datasource:
    url: jdbc:postgresql://localhost:3306/reporting-545_db
    username: webadmin
    password: Secure@321
  server:
    port: 8545
