spring:
  application:
    name: reporting-203-service
  datasource:
    url: jdbc:postgresql://localhost:3306/reporting-203_db
    username: webadmin
    password: Secure@321
  server:
    port: 8203
