spring:
  application:
    name: reporting-913-service
  datasource:
    url: jdbc:postgresql://localhost:3306/reporting-913_db
    username: appadmin
    password: Secure@321
  server:
    port: 8913
