spring:
  application:
    name: reporting-641-service
  datasource:
    url: jdbc:postgresql://localhost:3306/reporting-641_db
    username: appadmin
    password: Secure@321
  server:
    port: 8641
