spring:
  application:
    name: reporting-147-service
  datasource:
    url: jdbc:postgresql://localhost:3306/reporting-147_db
    username: webadmin
    password: Secure@321
  server:
    port: 8147
