spring:
  application:
    name: reporting-441-service
  datasource:
    url: jdbc:postgresql://localhost:3306/reporting-441_db
    username: appadmin
    password: Secure@321
  server:
    port: 8441
