spring:
  application:
    name: reporting-607-service
  datasource:
    url: jdbc:postgresql://localhost:3306/reporting-607_db
    username: appadmin
    password: Secure@321
  server:
    port: 8607
