spring:
  application:
    name: reporting-955-service
  datasource:
    url: jdbc:postgresql://localhost:3306/reporting-955_db
    username: appadmin
    password: Secure@321
  server:
    port: 8955
