spring:
  application:
    name: reporting-867-service
  datasource:
    url: jdbc:postgresql://localhost:3306/reporting-867_db
    username: webadmin
    password: Secure@321
  server:
    port: 8867
