spring:
  application:
    name: reporting-528-service
  datasource:
    url: jdbc:postgresql://localhost:3306/reporting-528_db
    username: appadmin
    password: Secure@321
  server:
    port: 8528
