spring:
  application:
    name: reporting-794-service
  datasource:
    url: jdbc:postgresql://localhost:3306/reporting-794_db
    username: appadmin
    password: Secure@321
  server:
    port: 8794
