spring:
  application:
    name: reporting-261-service
  datasource:
    url: jdbc:postgresql://localhost:3306/reporting-261_db
    username: webadmin
    password: Secure@321
  server:
    port: 8261
