spring:
  application:
    name: reporting-132-service
  datasource:
    url: jdbc:postgresql://localhost:3306/reporting-132_db
    username: appadmin
    password: Secure@321
  server:
    port: 8132
