spring:
  application:
    name: reporting-401-service
  datasource:
    url: jdbc:postgresql://localhost:3306/reporting-401_db
    username: appadmin
    password: Secure@321
  server:
    port: 8401
