spring:
  application:
    name: reporting-599-service
  datasource:
    url: jdbc:postgresql://localhost:3306/reporting-599_db
    username: webadmin
    password: Secure@321
  server:
    port: 8599
