spring:
  application:
    name: reporting-750-service
  datasource:
    url: jdbc:postgresql://localhost:3306/reporting-750_db
    username: appadmin
    password: Secure@321
  server:
    port: 8750
