spring:
  application:
    name: reporting-740-service
  datasource:
    url: jdbc:postgresql://localhost:3306/reporting-740_db
    username: appadmin
    password: Secure@321
  server:
    port: 8740
