spring:
  application:
    name: reporting-881-service
  datasource:
    url: jdbc:postgresql://localhost:3306/reporting-881_db
    username: appadmin
    password: Secure@321
  server:
    port: 8881
