spring:
  application:
    name: reporting-392-service
  datasource:
    url: jdbc:postgresql://localhost:3306/reporting-392_db
    username: appadmin
    password: Secure@321
  server:
    port: 8392
