spring:
  application:
    name: reporting-283-service
  datasource:
    url: jdbc:postgresql://localhost:3306/reporting-283_db
    username: webadmin
    password: Secure@321
  server:
    port: 8283
