spring:
  application:
    name: reporting-426-service
  datasource:
    url: jdbc:postgresql://localhost:3306/reporting-426_db
    username: appadmin
    password: Secure@321
  server:
    port: 8426
