spring:
  application:
    name: reporting-353-service
  datasource:
    url: jdbc:postgresql://localhost:3306/reporting-353_db
    username: appadmin
    password: Secure@321
  server:
    port: 8353
