spring:
  application:
    name: reporting-435-service
  datasource:
    url: jdbc:postgresql://localhost:3306/reporting-435_db
    username: webadmin
    password: Secure@321
  server:
    port: 8435
