spring:
  application:
    name: reporting-708-service
  datasource:
    url: jdbc:postgresql://localhost:3306/reporting-708_db
    username: webadmin
    password: Secure@321
  server:
    port: 8708
