spring:
  application:
    name: reporting-709-service
  datasource:
    url: jdbc:postgresql://localhost:3306/reporting-709_db
    username: webadmin
    password: Secure@321
  server:
    port: 8709
