spring:
  application:
    name: reporting-473-service
  datasource:
    url: jdbc:postgresql://localhost:3306/reporting-473_db
    username: webadmin
    password: Secure@321
  server:
    port: 8473
