spring:
  application:
    name: reporting-423-service
  datasource:
    url: jdbc:postgresql://localhost:3306/reporting-423_db
    username: webadmin
    password: Secure@321
  server:
    port: 8423
