spring:
  application:
    name: reporting-812-service
  datasource:
    url: jdbc:postgresql://localhost:3306/reporting-812_db
    username: appadmin
    password: Secure@321
  server:
    port: 8812
