spring:
  application:
    name: reporting-796-service
  datasource:
    url: jdbc:postgresql://localhost:3306/reporting-796_db
    username: webadmin
    password: Secure@321
  server:
    port: 8796
