spring:
  application:
    name: reporting-205-service
  datasource:
    url: jdbc:postgresql://localhost:3306/reporting-205_db
    username: webadmin
    password: Secure@321
  server:
    port: 8205
