spring:
  application:
    name: reporting-847-service
  datasource:
    url: jdbc:postgresql://localhost:3306/reporting-847_db
    username: webadmin
    password: Secure@321
  server:
    port: 8847
