spring:
  application:
    name: reporting-849-service
  datasource:
    url: jdbc:postgresql://localhost:3306/reporting-849_db
    username: webadmin
    password: Secure@321
  server:
    port: 8849
