spring:
  application:
    name: reporting-425-service
  datasource:
    url: jdbc:postgresql://localhost:3306/reporting-425_db
    username: appadmin
    password: Secure@321
  server:
    port: 8425
