spring:
  application:
    name: reporting-349-service
  datasource:
    url: jdbc:postgresql://localhost:3306/reporting-349_db
    username: appadmin
    password: Secure@321
  server:
    port: 8349
