spring:
  application:
    name: reporting-754-service
  datasource:
    url: jdbc:postgresql://localhost:3306/reporting-754_db
    username: webadmin
    password: Secure@321
  server:
    port: 8754
