spring:
  application:
    name: reporting-654-service
  datasource:
    url: jdbc:postgresql://localhost:3306/reporting-654_db
    username: appadmin
    password: Secure@321
  server:
    port: 8654
