spring:
  application:
    name: reporting-839-service
  datasource:
    url: jdbc:postgresql://localhost:3306/reporting-839_db
    username: appadmin
    password: Secure@321
  server:
    port: 8839
