spring:
  application:
    name: reporting-212-service
  datasource:
    url: jdbc:postgresql://localhost:3306/reporting-212_db
    username: webadmin
    password: Secure@321
  server:
    port: 8212
