spring:
  application:
    name: reporting-846-service
  datasource:
    url: jdbc:postgresql://localhost:3306/reporting-846_db
    username: appadmin
    password: Secure@321
  server:
    port: 8846
