spring:
  application:
    name: reporting-272-service
  datasource:
    url: jdbc:postgresql://localhost:3306/reporting-272_db
    username: appadmin
    password: Secure@321
  server:
    port: 8272
