spring:
  application:
    name: reporting-347-service
  datasource:
    url: jdbc:postgresql://localhost:3306/reporting-347_db
    username: appadmin
    password: Secure@321
  server:
    port: 8347
