spring:
  application:
    name: reporting-785-service
  datasource:
    url: jdbc:postgresql://localhost:3306/reporting-785_db
    username: webadmin
    password: Secure@321
  server:
    port: 8785
