spring:
  application:
    name: reporting-910-service
  datasource:
    url: jdbc:postgresql://localhost:3306/reporting-910_db
    username: webadmin
    password: Secure@321
  server:
    port: 8910
