spring:
  application:
    name: reporting-760-service
  datasource:
    url: jdbc:postgresql://localhost:3306/reporting-760_db
    username: appadmin
    password: Secure@321
  server:
    port: 8760
