spring:
  application:
    name: reporting-103-service
  datasource:
    url: jdbc:postgresql://localhost:3306/reporting-103_db
    username: webadmin
    password: Secure@321
  server:
    port: 8103
