spring:
  application:
    name: reporting-597-service
  datasource:
    url: jdbc:postgresql://localhost:3306/reporting-597_db
    username: webadmin
    password: Secure@321
  server:
    port: 8597
